//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampDios.Modelos
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Miembros
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Miembros()
        {
            this.Comunidad = new HashSet<Comunidad>();
            this.DetalleFamilia = new HashSet<DetalleFamilia>();
            this.DetalleFamilia1 = new HashSet<DetalleFamilia>();
            this.DetalleGrupo = new HashSet<DetalleGrupo>();
            this.Finanzas = new HashSet<Finanzas>();
            this.HistoriaEspiritual = new HashSet<HistoriaEspiritual>();
            this.Iglesia = new HashSet<Iglesia>();
            this.Miembros1 = new HashSet<Miembros>();
            this.Zona = new HashSet<Zona>();
        }
    
        public int IdMiembro { get; set; }

        [Required]
        public string Nombres { get; set; }

        [Required]
        public string Apellidos { get; set; }

        [Required]
        public string DUI { get; set; }

        [Required]
        public string NIT { get; set; }

        [Required]
        [DataType(DataType.Date)]
        [DisplayName("Fecha de nacimiento")]
        public System.DateTime FechaNacimiento { get; set; }

        [Required]
        [Display(Name="Dirección")]
        public string Direccion { get; set; }
        
        [Display(Name="Dirección 1")]
        public string Direccion1 { get; set; }
        
        [Display(Name="Dirección 2")]
        public string Direccion2 { get; set; }

        [Required]
        [Display(Name="E-mail")]
        public string Email { get; set; }

        [Required]
        public string Tel { get; set; }

        [Required]
        public string Cel { get; set; }

        [Required]
        public int Sexo { get; set; }

        [Required]
        [Display(Name="Estado civil")]
        public int IdEstadoCivil { get; set; }

        [Required]
        [Display(Name="Profesió")]
        public Nullable<int> IdProfesion { get; set; }

        [Required]
        [Display(Name="Capacitación")]
        public Nullable<int> IdCapacitacion { get; set; }

        [Required]
        [Display(Name="Liderazgo pastoral")]
        public Nullable<int> IdRol { get; set; }
        

        [Display(Name="Hermano mayor")]
        public Nullable<int> IdHMayor { get; set; }

        [Required]
        [Display(Name="Liderazgo corporativo")]
        public Nullable<int> IdCorporativo { get; set; }
    
        public virtual Capacitaciones Capacitaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comunidad> Comunidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleFamilia> DetalleFamilia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleFamilia> DetalleFamilia1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleGrupo> DetalleGrupo { get; set; }
        public virtual EstadoCivil EstadoCivil { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Finanzas> Finanzas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoriaEspiritual> HistoriaEspiritual { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Iglesia> Iglesia { get; set; }
        public virtual LiderazgoCorporativo LiderazgoCorporativo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Miembros> Miembros1 { get; set; }
        public virtual Miembros Miembros2 { get; set; }
        public virtual Profesion Profesion { get; set; }
        public virtual Roles Roles { get; set; }
        public virtual Sexo Sexo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zona> Zona { get; set; }
    }
}
