//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampDios
{
    using System;
    using System.Collections.Generic;
    
    public partial class Miembro_Familiar
    {
        public int IdFamilia { get; set; }
        public string Nombre_del_Familiar { get; set; }
        public string Apellidos_del_Familiar { get; set; }
        public string Parentesco { get; set; }
        public int IdMiembro { get; set; }
        public string Nombre_Miembro { get; set; }
        public string Apellido_Miembro { get; set; }
    }
}
