//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampDios
{
    using System;
    using System.Collections.Generic;
    
    public partial class Miembros_full
    {
        public int IdMiembro { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string DUI { get; set; }
        public string NIT { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string Direccion { get; set; }
        public string Email { get; set; }
        public string Tel { get; set; }
        public string Cel { get; set; }
        public string EstadoCivil { get; set; }
        public int IdProfesion { get; set; }
        public string Profesion { get; set; }
        public int IdCapacitacion { get; set; }
        public string Capacitacion { get; set; }
        public int IdPastoreo { get; set; }
        public string Liderasgo_Pastoral { get; set; }
        public int IdCorporativo { get; set; }
        public string Liderasgo_Corporativo { get; set; }
    }
}
