//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampDios.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CampDiosEntities : DbContext
    {
        public CampDiosEntities()
            : base("name=CampDiosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aprendice> Aprendices { get; set; }
        public virtual DbSet<Capacitacione> Capacitaciones { get; set; }
        public virtual DbSet<Catalogo> Catalogoes { get; set; }
        public virtual DbSet<Catalogo_Detalles> Catalogo_Detalles { get; set; }
        public virtual DbSet<Comunidad> Comunidads { get; set; }
        public virtual DbSet<Familia> Familias { get; set; }
        public virtual DbSet<Grupo> Grupoes { get; set; }
        public virtual DbSet<HistoriaEspiritual> HistoriaEspirituals { get; set; }
        public virtual DbSet<Iglesia> Iglesias { get; set; }
        public virtual DbSet<LiderasgoCorporativo> LiderasgoCorporativoes { get; set; }
        public virtual DbSet<LiderasgoPastoral> LiderasgoPastorals { get; set; }
        public virtual DbSet<Miembro> Miembros { get; set; }
        public virtual DbSet<Parentesco> Parentescos { get; set; }
        public virtual DbSet<Pastore> Pastores { get; set; }
        public virtual DbSet<Profesion> Profesions { get; set; }
        public virtual DbSet<Programacion_de_Reunione> Programacion_de_Reuniones { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Tipo_Grupo> Tipo_Grupo { get; set; }
        public virtual DbSet<USUARIO> USUARIOS { get; set; }
        public virtual DbSet<Zona> Zonas { get; set; }
    }
}
