//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampDios.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catalogo_Detalles
    {
        public int IdCatalogoDetalles { get; set; }
        public int IdCatalogo { get; set; }
        public string Value { get; set; }
        public string Descripcion { get; set; }
    
        public virtual Catalogo Catalogo { get; set; }
    }
}
