//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampDios.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Familia
    {
        public int IdFamilia { get; set; }
        public int IdMiembro { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public int IdParentesco { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
    
        public virtual Miembro Miembro { get; set; }
        public virtual Miembro Miembro1 { get; set; }
        public virtual Parentesco Parentesco { get; set; }
    }
}
