//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampDios.Modelo
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Programacion_de_Reunione
    {
        public int IdProgramacion { get; set; }
        [Display(Name ="Nombre del grupo")]
        public int IdGrupo { get; set; }
        [Required]
        [DataType(DataType.DateTime)]
        [Display(Name = "Fecha y hora de reunión")]
        public System.DateTime Fecha { get; set; }
        [Required]
        [Display(Name = "Descripción")]
        public string Descripcion { get; set; }
    
        public virtual Grupo Grupo { get; set; }
    }
}
