//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampDios.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zona_Miembro
    {
        public int IdZona { get; set; }
        public string Zona { get; set; }
        public string Descripcion { get; set; }
        public string Direccion { get; set; }
        public int IdMiembro { get; set; }
        public string Nombre_Lider { get; set; }
        public string Apellidos_Lider { get; set; }
    }
}
